package com.resonant.game.audio;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.audio.AudioDevice;
import com.badlogic.gdx.utils.Disposable;

/**
 * Real-time PCM music synthesis. Runs on a daemon thread, fills an AudioDevice with samples
 * generated by {@link MusicSequencer}. The device's writeSamples() blocks when the buffer is
 * full, providing natural rate control.
 */
public class AudioEngine implements Disposable {

    private static final int SAMPLE_RATE = 44100;
    private static final int BUFFER_SIZE = 1024;

    private AudioDevice          device;
    private final MusicSequencer seq = new MusicSequencer();
    private final short[]        buffer = new short[BUFFER_SIZE];
    private volatile boolean     running;
    private Thread               thread;
    private double               t;       // current sample time (seconds)

    public void start() {
        if (running) return;
        try {
            device = Gdx.audio.newAudioDevice(SAMPLE_RATE, true); // mono
        } catch (Throwable e) {
            // Audio init failed — game still runs without sound
            device = null;
            return;
        }
        running = true;
        thread = new Thread(this::runLoop, "ResonantAudioEngine");
        thread.setDaemon(true);
        thread.start();
    }

    private void runLoop() {
        final double dt = 1.0 / SAMPLE_RATE;
        try {
            while (running) {
                for (int i = 0; i < BUFFER_SIZE; i++) {
                    double s = seq.sampleAt(t);
                    int v = (int) (s * 28000);
                    if (v >  32767) v =  32767;
                    if (v < -32768) v = -32768;
                    buffer[i] = (short) v;
                    t += dt;
                }
                device.writeSamples(buffer, 0, BUFFER_SIZE);
            }
        } catch (Throwable e) {
            // Swallow — audio thread death must not crash the game
        }
    }

    /** Marks the moment of a ring switch for SFX synthesis. */
    public void triggerSwitchSfx() {
        seq.queueSwitchSfx(t);
    }

    /** Marks the moment of player death (pitch-bend music down + thump). */
    public void triggerDeath() {
        seq.queueDeathSfx(t);
    }

    /** 0..1 phase within the current beat (for visual sync). */
    public float getBeatPhase() {
        return seq.getBeatPhase(t);
    }

    public void resumeMusic() {
        seq.setMusicGain(1.0);
    }

    public void duckMusic(double gain) {
        seq.setMusicGain(gain);
    }

    @Override
    public void dispose() {
        running = false;
        if (thread != null) {
            try { thread.join(300); } catch (InterruptedException ignored) {}
            thread = null;
        }
        if (device != null) {
            try { device.dispose(); } catch (Throwable ignored) {}
            device = null;
        }
    }
}
